name: tsu_maps
description: "TSU Maps"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lottie: ^3.3.2
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-BoldItalic.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Italic.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Light.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-LightItalic.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-MediumItalic.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf

  assets:
    - assets/animations/splash_animation.json